FROM centos:7
ARG NGINX_AGENT_PKG

# NGINX Instance Manager agent setup
RUN mkdir -p /deployment /etc/ssl/nginx
COPY $NGINX_AGENT_PKG /deployment/nginx-agent.rpm
RUN yum -y localinstall /deployment/nginx-agent.rpm
RUN rm /deployment/nginx-agent.rpm
COPY ./container/start.sh /deployment/
RUN chmod +x /deployment/start.sh && touch /.dockerenv

# Download certificate and key from the customer portal (https://account.f5.com)
# and copy to the build context
COPY ./container/nginx-repo.crt /etc/ssl/nginx/
COPY ./container/nginx-repo.key /etc/ssl/nginx/

# Install prerequisite packages:
RUN yum -y update \
	&& yum install -y wget ca-certificates epel-release \
	&& yum -y update \
	&& yum autoremove -y \
	&& yum -y clean all \
	&& rm -rf /var/cache/yum \
	&& wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/nginx-plus-7.4.repo \
#	&& wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/app-protect-7.repo \
#	&& yum install -y app-protect app-protect-attack-signatures
	&& yum install -y nginx-plus nginx-plus-module-njs nginx-plus-module-prometheus

# Forward request logs to Docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80
STOPSIGNAL SIGTERM

#CMD ["nginx", "-g", "daemon off;"]
CMD /deployment/start.sh
